name: Build Kivy Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: System dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          zip unzip wget git \
          openjdk-17-jdk \
          build-essential zlib1g-dev libffi-dev libssl-dev

    - name: Install Buildozer + P4A (FIX 404)
      run: |
        pip install --upgrade pip
        pip install buildozer cython setuptools==65.5.0
        pip install git+https://github.com/kivy/python-for-android.git

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk

        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip tools.zip

        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest

        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

        yes | sdkmanager --licenses

        sdkmanager \
          "platform-tools" \
          "platforms;android-30" \
          "build-tools;30.0.3"

        mkdir -p $HOME/android-sdk/tools/bin
        ln -sf $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
              $HOME/android-sdk/tools/bin/sdkmanager

    - name: Install Android NDK 25b (REQUIRED)
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip

    - name: Clean Buildozer
      run: rm -rf ~/.buildozer

    - name: Build APK
      env:
        ANDROID_HOME: $HOME/android-sdk
        ANDROID_SDK_ROOT: $HOME/android-sdk
        ANDROID_NDK_HOME: $HOME/.buildozer/android/platform/android-ndk-r25b
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      run: |
        export PATH=$HOME/android-sdk/tools/bin:$PATH
        export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
        export PATH=$HOME/android-sdk/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: My-Kivy-APK
        path: bin/*.apk
